import pandas as pd
import yaml
from datetime import datetime
from ai_summary import generate_ai_summary

def get_streak_badge(city, df):
    # Simple logic: check last 3 entries for "Clear"
    city_data = df[df['city'] == city].sort_values('date', ascending=False).head(3)
    if len(city_data) < 3: return ""
    
    conditions = city_data['condition'].tolist()
    if all(c == 'Clear' for c in conditions):
        return f"https://img.shields.io/badge/{city}-Sunny_Streak_🔥-orange"
    if all(c == 'Rain' for c in conditions):
        return f"https://img.shields.io/badge/{city}-Rainy_Streak_🌧️-blue"
    return ""

def update_readme():
    csv_path = "data/history.csv"
    try:
        df = pd.read_csv(csv_path)
    except:
        return # No data yet

    latest_df = df.sort_values('timestamp').groupby('city').tail(1)
    
    # Generate content
    ai_text = generate_ai_summary()
    date_now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Badge Generation
    badges_md = ""
    for _, row in latest_df.iterrows():
        temp_color = "red" if row['temp'] > 25 else "blue" if row['temp'] < 10 else "green"
        badges_md += f"![{row['city']}](https://img.shields.io/badge/{row['city']}-{row['temp']}°C-{temp_color}) "
        
        # Streak Badge
        streak_url = get_streak_badge(row['city'], df)
        if streak_url:
            badges_md += f"![Streak]({streak_url}) "
    
    # Table Generation
    table_md = "| City | Temp | Condition | Humidity | Wind |\n|---|---|---|---|---|\n"
    for _, row in latest_df.iterrows():
        table_md += f"| {row['city']} | {row['temp']}°C | {row['description']} | {row['humidity']}% | {row['wind_speed']} m/s |\n"

    readme_content = f"""
# 🌦️ Automated Weather Insight Logger

> **Auto-updates every 6 hours** with real-time data, insights, and charts.

[![Weather Update](https://github.com/USERNAME/REPO_NAME/actions/workflows/weather.yml/badge.svg)](https://github.com/USERNAME/REPO_NAME/actions/workflows/weather.yml)
[👉 **View Full Dashboard**](https://USERNAME.github.io/REPO_NAME/)

## ⚡ Current Status ({date_now})
{badges_md}

## 🤖 AI Daily Summary
_{ai_text}_

## 📊 Weather Snapshot
{table_md}

## 📈 Trends
![Temperature Trend](data/charts/temp_trend.png)

---
*Generated by GitHub Actions & Python*
"""
    
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme_content)

if __name__ == "__main__":
    update_readme()